// Generated by dia2code
#ifndef STATE__CELL__H
#define STATE__CELL__H


#include "ElementType.h"
#include "ContentType.h"

namespace state {

  /// class Cell - 
  class Cell {
    // Associations
    // Attributes
  private:
    ElementType tileElement;
    ContentType tileContent;
    // Operations
  public:
    Cell (ElementType element = neutral, ContentType content = nothing);
    ElementType getElement ();
    void setElement (ElementType element);
    ContentType getContent ();
    void setContent (ContentType content);
    // Setters and Getters
  };

};

#endif
