// Generated by dia2code
#ifndef STATE__CHARACTERTYPE__H
#define STATE__CHARACTERTYPE__H


namespace state {

  enum CharacterType {
    human     = 0,
    goblin     = 1,
    witch     = 2
  };

};

#endif
