// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H

#include <string>

namespace state {
  class Weapon;
}

#include "Direction.h"
#include "CharacterType.h"
#include "Weapon.h"

namespace state {

  /// class Character - 
  class Character {
    // Associations
    // Attributes
  private:
    float i;
    float j;
    int id;
    Direction direction;
    std::string name;
    CharacterType type;
    unsigned int pvCurrent;
    unsigned int pvMax;
    unsigned int pmCurrent;
    unsigned int pmMax;
    unsigned int paCurrent;
    unsigned int paMax;
    Weapon* weapon;
    // Operations
  public:
    Character (int id = 0, std::string nom = "", CharacterType type = human, int pv = 3, int pa = 3, int pm = 3);
    float getI ();
    void setI (float i);
    float getJ ();
    void setJ (float j);
    int getId ();
    void setId (int id);
    Direction getDirection ();
    void setDirection (Direction direction);
    void setDirection (int direction);
    std::string getName ();
    void setName (std::string name);
    CharacterType getType ();
    void setType ();
    Weapon* getWeapon ();
    void setWeapon (Weapon* weapon);
    void removeWeapon ();
    void setPv (unsigned int pv);
    void setPm (unsigned int pm);
    void setPa (unsigned int pa);
    unsigned int getPvCurrent ();
    unsigned int getPvMax ();
    unsigned int getPmCurrent ();
    unsigned int getPmMax ();
    unsigned int getPaCurrent ();
    unsigned int getPaMax ();
    void resetPv ();
    void resetPm ();
    void resetPa ();
    void removePv (int pv);
    void removePm (int pm);
    void removePa (int pa);
    // Setters and Getters
  };

};

#endif
