// Generated by dia2code
#ifndef STATE__CONTENTTYPE__H
#define STATE__CONTENTTYPE__H


namespace state {

  enum ContentType {
    nothing     = 0,
    house     = 1,
    tree     = 2,
    mountain     = 3
  };

};

#endif
