// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {

  /// class Element - 
  class Element {
    // Operations
  public:
    Element ();
    // Setters and Getters
  };

};

#endif
