// Generated by dia2code
#ifndef STATE__ELEMENTTYPE__H
#define STATE__ELEMENTTYPE__H


namespace state {

  enum ElementType {
    neutral     = 0,
    water     = 1,
    earth     = 2,
    fire     = 3,
    wind     = 4
  };

};

#endif
