// Generated by dia2code
#ifndef STATE__EVENT__H
#define STATE__EVENT__H


#include "StateEvent.h"
#include "EventType.h"

namespace state {

  /// class Event - 
  class Event {
    // Associations
    // Attributes
  private:
    StateEvent id;
    // Operations
  public:
    ~Event ();
    EventType getId ();
    // Setters and Getters
  };

};

#endif
