// Generated by dia2code
#ifndef STATE__FIGHT__H
#define STATE__FIGHT__H


namespace state {
  class Team;
  class SideQuest;
}

#include "SideQuest.h"
#include "Team.h"

namespace state {

  /// class Fight - 
  class Fight {
    // Associations
    // Attributes
  private:
    int turn;
    vector<Team&> teams;
    vector<SideQuest&> quest;
    // Operations
  public:
    void deploy (Team& team);
    void getQuest (SideQuest& quest);
    void updateQuest (int i);
    void delQuest (int i);
    // Setters and Getters
  };

};

#endif
