// Generated by dia2code
#ifndef STATE__FIGHT__H
#define STATE__FIGHT__H

#include <stdlib.h>
#include <vector>

namespace state {
  class Team;
}

#include "Team.h"

namespace state {

  /// class Fight - 
  class Fight {
    // Associations
    // Attributes
  private:
    int turn     = 1;
    int nb;
    Team* main;
    Team* opponent;
    // Operations
  public:
    Fight (Team* main, Team* opponent, int nb = -1);
    int getTurn ();
    int getNb ();
    Team* getTeam (std::size_t i);
    std::vector<Team*> getTeams ();
    std::vector<Character*> getCharacters (int i = -1);
    std::vector<Character*> getFightingCharacters (int i = -1);
    void endTurn ();
    // Setters and Getters
  };

};

#endif
