// Generated by dia2code
#ifndef STATE__FIGHT__H
#define STATE__FIGHT__H

#include <vector>

namespace state {
  class Team;
}

#include "Team.h"

namespace state {

  /// class Fight - 
  class Fight {
    // Associations
    // Attributes
  private:
    int turn     = 1;
    Team* main;
    Team* opponent;
    // Operations
  public:
    Fight (Team* main, Team* opponent);
    std::vector<Team*> getTeams ();
    std::vector<Character*> getFightingCharacters ();
    // Setters and Getters
  };

};

#endif
