// Generated by dia2code
#ifndef STATE__INVENTORY__H
#define STATE__INVENTORY__H

#include <vector>

namespace state {
  class Item;
}

#include "Item.h"

namespace state {

  /// class Inventory - 
  class Inventory {
    // Associations
    // Attributes
  private:
    std::vector<Item*> content;
    // Operations
  public:
    Inventory ();
    void addItem (Item& item);
    void delItem (Item* pItem);
    // Setters and Getters
  };

};

#endif
