// Generated by dia2code
#ifndef STATE__INVENTORY__H
#define STATE__INVENTORY__H


namespace state {
  class Item;
}

#include "Item.h"

namespace state {

  /// class Inventory - 
  class Inventory {
    // Associations
    // Attributes
  private:
    vector<Item&> content;
    // Operations
  public:
    addItem (Item& item);
    delItem (int i);
    // Setters and Getters
  };

};

#endif
