// Generated by dia2code
#ifndef STATE__INVENTORY__H
#define STATE__INVENTORY__H

#include <vector>
#include <memory>

namespace state {
  class Item;
}

#include "Item.h"

namespace state {

  /// class Inventory - 
  class Inventory {
    // Associations
    // Attributes
  private:
    std::vector<std::unique_ptr<Item>> content;
    // Operations
  public:
    void addItem (Item& item);
    void delItem (int i);
    // Setters and Getters
  };

};

#endif
