// Generated by dia2code
#ifndef STATE__KILLQUEST__H
#define STATE__KILLQUEST__H


namespace state {
  class MainQuest;
}

#include "MainQuest.h"
#include "CharacterType.h"

namespace state {

  /// class KillQuest - 
  class KillQuest : public state::MainQuest {
    // Associations
    // Attributes
  private:
    map<CharacterType,int> const goal;
    map<CharacterType,int> kills;
    // Operations
  public:
    KillQuest (map<CharacterType,int> goal, map<CharacterType,int> kills);
    String getDescription ();
    bool checkFinished ();
    // Setters and Getters
  };

};

#endif
