// Generated by dia2code
#ifndef STATE__MAINQUEST__H
#define STATE__MAINQUEST__H


namespace state {
  class Item;
}

#include "Item.h"

namespace state {

  /// class MainQuest - 
  class MainQuest {
    // Attributes
  protected:
    string description;
    bool finished;
    int xpReward;
    int goldReward;
    vector<Item> ItemsReward;
    // Operations
  public:
    String getDescription ();
    bool checkFinished ();
    // Setters and Getters
    void setDescription(const string& description);
    bool getFinished() const;
    void setFinished(bool finished);
    int getXpReward() const;
    void setXpReward(int xpReward);
    int getGoldReward() const;
    void setGoldReward(int goldReward);
    const vector<Item>& getItemsReward() const;
    void setItemsReward(const vector<Item>& ItemsReward);
  };

};

#endif
