// Generated by dia2code
#ifndef STATE__MAINTEAM__H
#define STATE__MAINTEAM__H

#include <vector>
#include <memory>

namespace state {
  class MainQuest;
  class Team;
}

#include "Team.h"
#include "MainQuest.h"

namespace state {

  /// class MainTeam - 
  class MainTeam : public state::Team {
    // Associations
    // Attributes
  private:
    std::vector<std::unique_ptr<MainQuest>> quests;
    // Operations
  public:
    void addQuest (MainQuest& quest);
    void delQuest (int i);
    // Setters and Getters
  };

};

#endif
