// Generated by dia2code
#ifndef STATE__MAINQUEST__H
#define STATE__MAINQUEST__H

#include <string>
#include <vector>
#include <memory>

namespace state {
  class Item;
}

#include "Item.h"

namespace state {

  /// class MainQuest - 
  class MainQuest {
    // Associations
    // Attributes
  protected:
    std::string description;
    bool finished;
    int xpReward;
    int goldReward;
    std::vector<std::unique_ptr<Item>> ItemsReward;
    // Operations
  public:
    MainQuest ();
    std::string getDescription ();
    bool checkFinished ();
    // Setters and Getters
    void setDescription(const std::string& description);
    bool getFinished() const;
    void setFinished(bool finished);
    int getXpReward() const;
    void setXpReward(int xpReward);
    int getGoldReward() const;
    void setGoldReward(int goldReward);
    const std::vector<std::unique_ptr<Item>>& getItemsReward() const;
    void setItemsReward(const std::vector<std::unique_ptr<Item>>& ItemsReward);
  };

};

#endif
