// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class Observer;
  class Event;
}

#include "Observer.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  private:
    std::vector<Observer*> observers;
    // Operations
  public:
    void registerObserver (Observer* o);
    void unregisterObserver (Observer* o);
    void unregisterObservers ();
    void notifyObservers (Event* e);
    // Setters and Getters
  };

};

#endif
