// Generated by dia2code
#ifndef STATE__OBSERVER__H
#define STATE__OBSERVER__H


namespace state {
  class Event;
}

#include "Event.h"

namespace state {

  /// class Observer - 
  class Observer {
    // Operations
  public:
    void stateChanged (Event* e);
    // Setters and Getters
  };

};

#endif
