// Generated by dia2code
#ifndef STATE__POSITION__H
#define STATE__POSITION__H

#include <stdlib.h>

namespace state {

  /// class Position - 
  class Position {
    // Attributes
  private:
    std::size_t i;
    std::size_t j;
    // Operations
  public:
    Position (std::size_t i, std::size_t j);
    void set (std::size_t i, std::size_t j);
    void setI (std::size_t i);
    void setJ (std::size_t j);
    std::size_t getI ();
    std::size_t getJ ();
    // Setters and Getters
  };

};

#endif
