// Generated by dia2code
#ifndef STATE__SIDEQUEST__H
#define STATE__SIDEQUEST__H


namespace state {

  /// class SideQuest - 
  class SideQuest {
    // Attributes
  private:
    string type;
    int number;
    int reputationReward;
    // Setters and Getters
  };

};

#endif
