// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class World;
}

#include "World.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  public:
    bool isInventoryOpened     = false;
  private:
    World world;
    bool isFighting     = false;
  protected:
    int epoch     = 0;
    int epochRate     = 15;
    // Operations
  public:
    State ();
    World& getWorld ();
    // Setters and Getters
    int getEpoch() const;
    void setEpoch(int epoch);
    int getEpochRate() const;
    void setEpochRate(int epochRate);
  };

};

#endif
