// Generated by dia2code
#ifndef STATE__STATMODIFIER__H
#define STATE__STATMODIFIER__H


namespace state {

  /// class StatModifier - 
  class StatModifier {
    // Attributes
  private:
    string type;
    int value;
    // Setters and Getters
  };

};

#endif
