// Generated by dia2code
#ifndef STATE__TABELEMENT__H
#define STATE__TABELEMENT__H

#include <stdlib.h>
#include <vector>
#include <memory>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class TabElement - 
  class TabElement {
    // Associations
    // Attributes
  private:
    std::size_t width;
    std::size_t height;
    std::vector<std::unique_ptr<Element>> list;
    // Operations
  public:
    TabElement (std::size_t width = 0, std::size_t height = 1);
    std::size_t const getWidth ();
    std::size_t const getHeight ();
    void add (Element* e);
    Element* const get (int i, int j = 0);
    void set (Element* e, int i, int j = 0);
    void del (int i, int j = 0);
    // Setters and Getters
  };

};

#endif
