// Generated by dia2code
#ifndef STATE__WEAPON__H
#define STATE__WEAPON__H

#include <vector>
#include <memory>

namespace state {
  class Ability;
  class Item;
}

#include "ElementType.h"
#include "Item.h"
#include "Ability.h"

namespace state {

  /// class Weapon - 
  class Weapon : public state::Item {
    // Associations
    // Attributes
  private:
    std::vector<std::unique_ptr<Ability>> abilities;
    ElementType element;
    // Operations
  public:
    Weapon (ElementType element);
    void addAbility (Ability& ability);
    void delAbility (int i);
    // Setters and Getters
  };

};

#endif
