// Generated by dia2code
#ifndef STATE__WEAPON__H
#define STATE__WEAPON__H


namespace state {
  class Ability;
  class StatModifier;
  class Item;
}

#include "ElementType.h"
#include "Item.h"
#include "StatModifier.h"
#include "Ability.h"

namespace state {

  /// class Weapon - 
  class Weapon : public state::Item {
    // Associations
    // Attributes
  private:
    vector<Ability&> abilities;
    ElementType element;
    vector<StatModifier&> stats;
    // Operations
  public:
    Weapon (ElementType element);
    void addAbility (Ability& ability);
    void delAbility (int i);
    void addStat (StatModifier& stat);
    void delStat (int i);
    // Setters and Getters
  };

};

#endif
