// Generated by dia2code
#ifndef STATE__WORLD__H
#define STATE__WORLD__H


namespace state {
  class Cell;
}

#include "Cell.h"

namespace state {

  /// class World - 
  class World {
    // Associations
    // Attributes
  private:
    int row;
    int column;
    vector<vector<Cell&>> grid;
    // Operations
  public:
    World (int row, int column);
    vector<vector<Cell&>> getGrid ();
    Cell& getCell (int i, int j);
    void setCell (int i, int j, Cell& cell);
    // Setters and Getters
  };

};

#endif
