// Generated by dia2code
#ifndef STATE__ZONETYPE__H
#define STATE__ZONETYPE__H


namespace state {

  enum ZoneType {
    close     = 0,
    circle     = 1,
    line     = 2,
    diag     = 3
  };

};

#endif
