// Generated by dia2code
#ifndef __SERVER__H
#define __SERVER__H

#include "server/HttpStatus.h"
#include "server/AbstractService.h"
#include "server/ServiceException.h"
#include "server/ServicesManager.h"
#include "server/Player.h"
#include "server/GameStatus.h"
#include "server/Game.h"
#include "server/PlayerService.h"
#include "server/VersionService.h"
#include "server/GameService.h"
#include "server/CommandsService.h"
#include "server/User.h"
#include "server/UserDB.h"
#include "server/UserService.h"
#endif
