// Generated by dia2code
#ifndef RENDER__ABILITYSPRITE__H
#define RENDER__ABILITYSPRITE__H

#include <SFML/Graphics.hpp>

namespace render {

  /// class AbilitySprite - 
  class AbilitySprite {
    // Attributes
  private:
    sf::Texture texture;
    sf::Sprite sprite;
    int l;
    int h;
    // Operations
  public:
    AbilitySprite (int l, int h);
    sf::Sprite getSprite (int element, unsigned int lv);
    // Setters and Getters
  };

};

#endif
