// Generated by dia2code
#ifndef RENDER__BUTTON__H
#define RENDER__BUTTON__H


namespace render {
  class Rectangle;
}

#include "Rectangle.h"

namespace render {

  /// class Button - 
  class Button : public render::Rectangle {
    // Operations
  public:
    Button ();
    // Setters and Getters
  };

};

#endif
