// Generated by dia2code
#ifndef RENDER__BUTTON__H
#define RENDER__BUTTON__H


namespace render {
  class Element;
}

#include "Element.h"

namespace render {

  /// class Button - 
  class Button : public render::Element {
    // Operations
  public:
    Button ();
    // Setters and Getters
  };

};

#endif
