// Generated by dia2code
#ifndef RENDER__CHARACTERSPRITE__H
#define RENDER__CHARACTERSPRITE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class Texture;
  class Sprite;
}


namespace render {

  /// class CharacterSprite - 
  class CharacterSprite {
    // Attributes
  private:
    sf::Texture texture;
    sf::Sprite sprite;
    int l;
    int h;
    // Operations
  public:
    CharacterSprite (std::string filename, int l, int h);
    sf::Sprite getSprite (int id = 0, int direction = 0, int animation = 1);
    // Setters and Getters
  };

};

#endif
