// Generated by dia2code
#ifndef RENDER__COMPUTEMETHODTYPE__H
#define RENDER__COMPUTEMETHODTYPE__H


namespace render {

  enum ComputeMethodType {
    pixel,
    percent,
    alignement
  };

};

#endif
