// Generated by dia2code
#ifndef RENDER__CONTENTSPRITE__H
#define RENDER__CONTENTSPRITE__H

#include <vector>
#include <SFML/Graphics.hpp>

namespace sf {
  class Texture;
  class Sprite;
}


namespace render {

  /// class ContentSprite - 
  class ContentSprite {
    // Attributes
  private:
    std::vector<sf::Texture> textures;
    std::vector<sf::Sprite> sprites;
    std::vector<std::vector<int>> dimensions;
    std::vector<std::vector<std::vector<int>>> offsets;
    int l;
    int h;
    std::vector<int> offsetI;
    std::vector<int> offsetJ;
    // Operations
  public:
    ContentSprite (int l, int h);
    sf::Sprite getSprite (int content, int element = 0);
    // Setters and Getters
  };

};

#endif
