// Generated by dia2code
#ifndef RENDER__CONTENTSPRITE__H
#define RENDER__CONTENTSPRITE__H

#include <SFML/Graphics.hpp>
#include <vector>
#include <string>

namespace sf {
  class Texture;
  class Sprite;
}


namespace render {

  /// class ContentSprite - 
  class ContentSprite {
    // Attributes
  private:
    sf::Texture texture;
    sf::Sprite sprite;
    int l;
    int h;
    std::vector<int> offsetI;
    std::vector<int> offsetJ;
    // Operations
  public:
    ContentSprite (std::string filename, int l, int h, std::vector<int> offsetI, std::vector<int> offsetJ);
    sf::Sprite getSprite (int element);
    // Setters and Getters
  };

};

#endif
