// Generated by dia2code
#ifndef RENDER__DISPLAYSTATE__H
#define RENDER__DISPLAYSTATE__H

#include <vector>

namespace state {
  class State;
};
namespace render {
  class TileSprite;
  class CharacterSprite;
}

#include "CharacterSprite.h"
#include "TileSprite.h"
#include "state/State.h"

namespace render {

  /// class DisplayState - 
  class DisplayState {
    // Associations
    // Attributes
  private:
    state::State* state;
    std::vector<TileSprite*> tiles;
    std::vector<CharacterSprite*> characters;
    // Operations
  public:
    DisplayState (state::State* state);
    void addTile (TileSprite* tileSprite);
    void addCharacter (CharacterSprite* characterSprite);
    void display ();
    // Setters and Getters
  };

};

#endif
