// Generated by dia2code
#ifndef RENDER__ELEMENTCOMPOSITE__H
#define RENDER__ELEMENTCOMPOSITE__H

#include <vector>
#include <SFML/Graphics.hpp>

namespace render {
  class Element;
}

#include "Element.h"

namespace render {

  /// class ElementComposite - 
  class ElementComposite : public render::Element {
    // Associations
    // Attributes
  public:
    std::vector<Element*> children;
    // Operations
  public:
    void transmitEvent (sf::Event event, sf::Vector2f posMouse);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    // Setters and Getters
  };

};

#endif
