// Generated by dia2code
#ifndef RENDER__ELEMENT__H
#define RENDER__ELEMENT__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>
#include <vector>
#include <string>
#include <ostream>

namespace render {
  class Element;
  class Relatif2;
  class Relatif;
};
namespace sf {
  class Drawable;
}

#include "Relatif2.h"
#include "Relatif.h"

namespace render {

  /// class Element - 
  class Element : public sf::Drawable {
    // Associations
    // Attributes
  public:
    bool waitingDestruction     = false;
  private:
    Element* pparent     = nullptr;
    std::vector<Element*> pchildren;
    unsigned int depthCache     = 0;
    Relatif2 posRelative;
    sf::Vector2f posAbsCache;
    Relatif2 sizeRelative;
    sf::Vector2f sizeAbsCache;
    static int created;
    int id;
    bool mouseOverCache;
    Element* link     = nullptr;
    // Operations
  public:
    Element ();
    ~Element ();
    Element (const Element& obj);
    virtual Element& operator= (const Element& obj);
    virtual void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    const Relatif2 getPosRelative () const;
    void setPosRelative (Relatif2 posRelatif);
    virtual void updatePosAbs ();
    const sf::Vector2f getPosAbs () const;
    void setPosAbs (const sf::Vector2f pos);
    virtual void reactEditPosAbsParent ();
    void notifyEditPosAbs ();
    const Relatif2 getSizeRelative () const;
    void setSizeRelative (Relatif2 sizeRelatif);
    virtual void updateSizeAbs ();
    const sf::Vector2f getSizeAbs () const;
    void setSizeAbs (const sf::Vector2f size);
    void notifyEditSizeAbs ();
    virtual void reactEditSizeAbsParent ();
    void notifyEvent (sf::Event event, sf::Vector2f mousePosAbs);
    void reactEvent (sf::Event event, sf::Vector2f mousePosAbs);
    Element* getParent () const;
    void setParent (Element* pparent);
    void add (Element* pchild);
    void remove (Element* pchild);
    unsigned int getDepth () const;
    std::string posToStr (sf::Vector2f pos) const;
    std::string getTreeView () const;
    friend std::ostream& operator<< (std::ostream& os, const Element& el);
    friend std::ostream& operator<< (std::ostream& os, const sf::Vector2f& vec);
    bool isInside (sf::Vector2f posAbs);
    int getId () const;
    bool getWaitingDestruction () const;
    void moveAtTop (Element* pchild);
    bool getMouseOver () const;
    void setMouseOver (bool b, sf::Vector2f mousePosAbs);
    bool getMouseInChildren (sf::Vector2f mousePos) const;
    void closeChildrenWaiting ();
    void updateChildrenMouseOver (sf::Vector2f mousePosAbs);
    std::vector<Element*> getChildren () const;
    void setChildren (std::vector<Element*> pchildren);
    Element* getChild (Element* child);
    virtual Element* getCopy () const;
    void setLink (Element* link);
    Element* getLink ();
    std::vector<Element*> getLinked ();
    std::vector<Element*> getLinks ();
  private:
    void updateDepth ();
    float computeCoord (Relatif rel, float parentCoordAbs, float parentLengthAbs, float lengthAbs);
    float computeLength (Relatif rel, float parentLengthAbs);
  protected:
    void setWaitingDestruction (bool b);
    virtual void processEvent (sf::Event event, sf::Vector2f mousePos);
    // Setters and Getters
  };

};

#endif
