// Generated by dia2code
#ifndef RENDER__INVENTORY__H
#define RENDER__INVENTORY__H


namespace render {
  class Window;
}

#include "Window.h"

namespace render {

  /// class Inventory - 
  class Inventory : public render::Window {
    // Setters and Getters
  };

};

#endif
