// Generated by dia2code
#ifndef RENDER__RECTANGLE__H
#define RENDER__RECTANGLE__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>

namespace render {
  class Rectangle;
  class Element;
}

#include "Element.h"

namespace render {

  /// class Rectangle - 
  class Rectangle : public render::Element {
    // Attributes
  public:
    sf::RectangleShape recshape;
    // Operations
  public:
    Rectangle ();
    Rectangle (const Rectangle& obj);
    ~Rectangle ();
    Rectangle& operator= (const Rectangle& rec);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    void updatePosAbs ();
    void updateSizeAbs ();
    virtual Element* getCopy () const;
    // Setters and Getters
  };

};

#endif
