// Generated by dia2code
#ifndef RENDER__RELATIF2__H
#define RENDER__RELATIF2__H

#include <SFML/Graphics.hpp>
#include <ostream>

namespace render {
  class Relatif;
  class Relatif2;
}

#include "Relatif.h"

namespace render {

  /// class Relatif2 - 
  class Relatif2 {
    // Associations
    // Attributes
  public:
    Relatif x;
    Relatif y;
    // Operations
  public:
    Relatif2 ();
    Relatif2 (Relatif x, Relatif y);
    Relatif2 (sf::Vector2f pos);
    friend std::ostream& operator<< (std::ostream& os, const Relatif2& rel2);
    // Setters and Getters
  };

};

#endif
