// Generated by dia2code
#ifndef RENDER__RELATIF2__H
#define RENDER__RELATIF2__H


namespace render {
  class Relatif;
}

#include "Relatif.h"

namespace render {

  /// class Relatif2 - 
  class Relatif2 {
    // Associations
    // Attributes
  public:
    Relatif x;
    Relatif y;
    // Operations
  public:
    Relatif2 ();
    Relatif2 (Relatif x, Relatif y);
    operator std::string () const;
    // Setters and Getters
  };

};

#endif
