// Generated by dia2code
#ifndef RENDER__RELATIF__H
#define RENDER__RELATIF__H

#include <string>

namespace render {

  /// class Relatif - 
  class Relatif {
    // Attributes
  private:
    int computeMethod     = 0;
    float offset     = 0;
    float percent     = 0;
    std::string alignement;
    // Operations
  public:
    Relatif ();
    Relatif (int offset);
    Relatif (float offset);
    Relatif (std::string str);
    void operator= (int offset);
    void operator= (float offset);
    void operator= (std::string str);
    int getComputeMethod () const;
    float getOffset () const;
    float getPercent () const;
    std::string getAlignement () const;
    // Setters and Getters
  };

};

#endif
