// Generated by dia2code
#ifndef RENDER__RENDER__H
#define RENDER__RENDER__H


namespace state {
  class State;
};
namespace render {
  class ContentSprite;
  class CharacterSprite;
  class TileSprite;
}

#include "ContentSprite.h"
#include "CharacterSprite.h"
#include "TileSprite.h"
#include "state/State.h"

namespace render {

  /// class Render - 
  class Render {
    // Associations
    // Attributes
  private:
    state::State* state;
    // Operations
  public:
    Render (state::State* state);
    void display ();
    // Setters and Getters
  };

};

#endif
