// Generated by dia2code
#ifndef RENDER__SPRITE__H
#define RENDER__SPRITE__H

#include <SFML/Graphics.hpp>

namespace render {
  class Element;
}

#include "Element.h"

namespace render {

  /// class Sprite - 
  class Sprite : public render::Element {
    // Attributes
  public:
    sf::Sprite sprite;
    // Operations
  public:
    Sprite ();
    ~Sprite ();
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    void updatePosAbs ();
    void updateSizeFromTextureRect ();
    void updateSizeAbs ();
    // Setters and Getters
  };

};

#endif
