// Generated by dia2code
#ifndef RENDER__SPRITES__H
#define RENDER__SPRITES__H

#include <SFML/Graphics.hpp>

namespace render {

  /// class Sprites - 
  class Sprites {
    // Attributes
  private:
    sf::Texture texture;
    sf::Sprite sprite;
    // Operations
  public:
    Sprites ();
    sf::Sprite getTileSprite (int l, int h, int element);
    sf::Sprite getContentSprite (int l, int h, int content, int element = 0);
    sf::Sprite getCharacterSprite (int l, int h, int id, int direction = 0, int animation = 1);
    sf::Sprite getAbilitySprite (int l, int h, int element, unsigned int lv);
    sf::Sprite getAttackSprite (int l, int h, int direction, int element, int lv);
    // Setters and Getters
  };

};

#endif
