// Generated by dia2code
#ifndef RENDER__TILESPRITE__H
#define RENDER__TILESPRITE__H

#include <vector>
#include <SFML/Graphics.hpp>

namespace render {

  /// class TileSprite - 
  class TileSprite {
    // Attributes
  private:
    std::vector<sf::Texture> textures;
    std::vector<sf::Sprite> sprites;
    int l;
    int h;
    int nbRepeat;
    // Operations
  public:
    TileSprite (int l, int h, int nbRepeat = 3);
    sf::Sprite getSprite (int element);
    // Setters and Getters
  };

};

#endif
