// Generated by dia2code
#ifndef RENDER__TILESPRITE__H
#define RENDER__TILESPRITE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class Texture;
  class Sprite;
}


namespace render {

  /// class TileSprite - 
  class TileSprite {
    // Attributes
  private:
    sf::Texture texture;
    sf::Sprite sprite;
    int l;
    int h;
    int nbRepeat;
    // Operations
  public:
    TileSprite (std::string filename, int l, int h, int nbRepeat = 2);
    sf::Sprite getSprite ();
    // Setters and Getters
  };

};

#endif
