// Generated by dia2code
#ifndef RENDER__TITLEBARBUTTON__H
#define RENDER__TITLEBARBUTTON__H


namespace render {
  class Button;
}

#include "Button.h"

namespace render {

  /// class TitleBarButton - 
  class TitleBarButton : public render::Button {
    // Operations
  public:
    TitleBarButton ();
    // Setters and Getters
  };

};

#endif
