// Generated by dia2code
#ifndef RENDER__TITLEBAR__H
#define RENDER__TITLEBAR__H

#include <string>
#include <vector>

namespace render {
  class TitleBarButton;
  class ElementComposite;
}

#include "ElementComposite.h"
#include "TitleBarButton.h"

namespace render {

  /// class TitleBar - 
  class TitleBar : public render::ElementComposite {
    // Associations
    // Attributes
  public:
    std::string title;
    std::vector<TitleBarButton*> buttons;
    float height;
    // Operations
  public:
    TitleBar ();
    // Setters and Getters
  };

};

#endif
