// Generated by dia2code
#ifndef RENDER__TITLEBAR__H
#define RENDER__TITLEBAR__H

#include <string>
#include <vector>

namespace render {
  class TitleBarButton;
  class ElementComposite;
}

#include "ElementComposite.h"
#include "TitleBarButton.h"

namespace render {

  /// class TitleBar - 
  class TitleBar : public render::ElementComposite {
    // Associations
    // Attributes
  protected:
    std::string title;
    std::vector<TitleBarButton*> buttons;
    // Operations
  public:
    TitleBar ();
    // Setters and Getters
    const std::string& getTitle() const;
    void setTitle(const std::string& title);
    const std::vector<TitleBarButton*>& getButtons() const;
    void setButtons(const std::vector<TitleBarButton*>& buttons);
  };

};

#endif
