// Generated by dia2code
#ifndef RENDER__VIEW__H
#define RENDER__VIEW__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>

namespace render {
  class Element;
}

#include "Element.h"

namespace render {

  /// class View - 
  class View : public render::Element {
    // Attributes
  public:
    sf::View view;
    // Operations
  public:
    View ();
    ~View ();
    void updatePosAbs ();
    void updateSizeAbs ();
    sf::Vector2f getCenter ();
    sf::Vector2f getSize ();
    // Setters and Getters
  };

};

#endif
