// Generated by dia2code
#ifndef RENDER__WINDOW__H
#define RENDER__WINDOW__H

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>

namespace render {
  class Rectangle;
  class Text;
  class Window;
  class Element;
}

#include "Rectangle.h"
#include "Text.h"

namespace render {

  /// class Window - 
  class Window : public render::Rectangle {
    // Associations
    // Attributes
  public:
    Rectangle* ptitleBar;
    Text* ptitle;
    Rectangle* pcloseBtn;
    Rectangle* pcontent;
  private:
    sf::Vector2f mouseOffset;
    bool isDraging     = false;
    // Operations
  public:
    Window ();
    void processEvent (sf::Event event, sf::Vector2f mousePosAbs);
    Window (const Window& win);
    Window& operator= (const Window& win);
    Element* getCopy () const;
    // Setters and Getters
  };

};

#endif
