// Generated by dia2code
#ifndef RENDER__WINDOW__H
#define RENDER__WINDOW__H


namespace render {
  class TitleBar;
  class Element;
  class ElementComposite;
}

#include "ElementComposite.h"
#include "TitleBar.h"

namespace render {

  /// class Window - 
  class Window : public render::ElementComposite {
    // Associations
    // Attributes
  public:
    TitleBar* ptitleBar;
    Element* pcontent;
    bool wantToClose     = false;
    // Operations
  public:
    Window ();
    bool getWantToClose ();
    // Setters and Getters
  };

};

#endif
