// Generated by dia2code
#ifndef RENDER__WINDOWMANAGER__H
#define RENDER__WINDOWMANAGER__H

#include <SFML/Graphics.hpp>

namespace render {
  class Inventory;
  class ElementComposite;
}

#include "ElementComposite.h"

namespace render {

  /// class WindowManager - 
  class WindowManager : public render::ElementComposite {
    // Attributes
  public:
    Inventory* inventory;
    // Operations
  public:
    WindowManager ();
    void receiveEvent (sf::Event event, sf::Vector2f posMouse);
  private:
    void toggleInventory ();
    // Setters and Getters
  };

};

#endif
