// Generated by dia2code
#ifndef RENDER__WINDOWTEST__H
#define RENDER__WINDOWTEST__H


namespace render {
  class Window;
}

#include "Window.h"

namespace render {

  /// class WindowTest - 
  class WindowTest : public render::Window {
    // Operations
  public:
    WindowTest ();
    // Setters and Getters
  };

};

#endif
