// Generated by dia2code
#ifndef AI__DEEPAI__H
#define AI__DEEPAI__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Engine;
};
namespace state {
  class Character;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class DeepAI - 
  class DeepAI : public ai::AI {
    // Operations
  public:
    DeepAI (state::State* state, engine::Engine* engine);
    std::vector<state::Character*> getTurnOrder (std::vector<state::Character*> characters);
    void run (state::Character* character);
    // Setters and Getters
  };

};

#endif
