// Generated by dia2code
#ifndef AI__SCORE__H
#define AI__SCORE__H


namespace ai {

  /// class Score - 
  class Score {
    // Attributes
  public:
    int bonusDmgEnnemy     = 0;
    int malusDmgAlly     = 0;
    int bonusCloser     = 0;
    int malusPaUsed     = 0;
    int malusPmUsed     = 0;
    // Operations
  public:
    int getScore ();
    // Setters and Getters
  };

};

#endif
