// Generated by dia2code
#ifndef AI__TREENODE__H
#define AI__TREENODE__H

#include <memory>
#include <vector>

namespace ai {
  class TreeNode;
};
namespace state {
  class Character;
};
namespace engine {
  class Command;
};
namespace ai {
  class Score;
}

#include "Score.h"
#include "engine/Command.h"

namespace ai {

  /// class TreeNode - 
  class TreeNode {
    // Associations
    // Attributes
  public:
    std::shared_ptr<TreeNode> parent;
    std::vector<std::shared_ptr<TreeNode>> children;
    state::Character* character;
    int score;
    int teamNumber;
    std::vector<engine::Command*> commands;
    // Setters and Getters
  };

};

#endif
