// Generated by dia2code
#ifndef ENGINE__ANIMATIONCOMMAND__H
#define ENGINE__ANIMATIONCOMMAND__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class AnimationCommand - 
  class AnimationCommand : public engine::Command {
    // Attributes
  private:
    std::vector<std::vector<int>> positions;
    std::vector<int> directions;
    int element;
    int lv;
    // Operations
  public:
    AnimationCommand (state::State* state, std::vector<std::vector<int>> positions, std::vector<int> directions, int element, int lv);
    void execute ();
    // Setters and Getters
  };

};

#endif
