// Generated by dia2code
#ifndef ENGINE__ATTACKCOMMAND__H
#define ENGINE__ATTACKCOMMAND__H

#include <vector>
#include <stdlib.h>

namespace state {
  class Ability;
  class State;
  class Character;
};
namespace engine {
  class Command;
}

#include "Command.h"
#include "state/Ability.h"

namespace engine {

  /// class AttackCommand - 
  class AttackCommand : public engine::Command {
    // Associations
    // Attributes
  private:
    int abilityNumber;
    std::vector<int> position;
    std::vector<std::vector<int>> targets;
    std::vector<std::vector<int>> effects;
    state::Ability* ability;
    // Operations
  public:
    AttackCommand (state::State* state, state::Character* character, std::vector<int> position, int abilityNumber = 0);
    void setZones ();
    std::vector<std::vector<int>> getZone (std::size_t i);
    void execute ();
    // Setters and Getters
  };

};

#endif
