// Generated by dia2code
#ifndef ENGINE__ATTACKCOMMAND__H
#define ENGINE__ATTACKCOMMAND__H

#include <vector>
#include <stdlib.h>
#include <json/json.h>

namespace state {
  class Ability;
  class State;
};
namespace engine {
  class Engine;
};
namespace state {
  class Character;
};
namespace engine {
  class AttackCommand;
  class Command;
}

#include "Command.h"
#include "state/Ability.h"

namespace engine {

  /// class AttackCommand - 
  class AttackCommand : public engine::Command {
    // Associations
    // Attributes
  private:
    int abilityNumber;
    std::vector<int> position;
    std::vector<std::vector<int>> targets;
    std::vector<std::vector<int>> effects;
    state::Ability* ability;
    // Operations
  public:
    AttackCommand (state::State* state, Engine* engine, state::Character* character, std::vector<int> position, int abilityNumber = 0, bool reverse = false);
    void offsetPosition (std::vector<int> offset);
    int getAbilityNumber ();
    void setZones (bool cut = true);
    std::vector<std::vector<int>> getZone (std::size_t i, bool cut = true);
    void execute ();
    void const serialize (Json::Value& out);
    static AttackCommand* deserialize (const Json::Value& in, state::State* state, engine::Engine* engine = nullptr);
    // Setters and Getters
  };

};

#endif
