// Generated by dia2code
#ifndef ENGINE__CLEARCOMMAND__H
#define ENGINE__CLEARCOMMAND__H


namespace engine {
  class Engine;
}

namespace engine {

  /// class ClearCommand - 
  class ClearCommand {
    // Operations
  public:
    ClearCommand (Engine* engine);
    void execute ();
    // Setters and Getters
  };

};

#endif
