// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H


namespace state {
  class State;
}

#include "state/State.h"

namespace engine {

  /// class Command - 
  class Command {
    // Associations
    // Attributes
  protected:
    state::State* state;
    // Operations
  public:
    virtual ~Command ();
    virtual void execute ();
    // Setters and Getters
    const state::State*& getState() const;
    void setState(const state::State*& state);
  };

};

#endif
