// Generated by dia2code
#ifndef ENGINE__DAMAGECOMMAND__H
#define ENGINE__DAMAGECOMMAND__H

#include <vector>
#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Engine;
  class DamageCommand;
  class Command;
}

#include "Command.h"

namespace engine {

  /// class DamageCommand - 
  class DamageCommand : public engine::Command {
    // Attributes
  private:
    std::vector<std::vector<int>> positions;
    std::vector<int> directions;
    int element;
    int lv;
    bool heal;
    int dmg;
    // Operations
  public:
    DamageCommand (state::State* state, Engine* engine, std::vector<std::vector<int>> positions, std::vector<int> directions, int element, int lv, bool heal = false, int dmg = 0, bool reverse = false);
    void execute ();
    void const serialize (Json::Value& out);
    static DamageCommand* deserialize (const Json::Value& in, state::State* state, engine::Engine* engine = nullptr);
    // Setters and Getters
  };

};

#endif
