// Generated by dia2code
#ifndef ENGINE__DAMAGECOMMAND__H
#define ENGINE__DAMAGECOMMAND__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Engine;
  class Command;
}

#include "Command.h"

namespace engine {

  /// class DamageCommand - 
  class DamageCommand : public engine::Command {
    // Attributes
  private:
    std::vector<std::vector<int>> positions;
    std::vector<int> directions;
    int element;
    int lv;
    int dmg;
    // Operations
  public:
    DamageCommand (state::State* state, Engine* engine, std::vector<std::vector<int>> positions, std::vector<int> directions, int element, int lv, int dmg = 0, bool reverse = false);
    void execute ();
    // Setters and Getters
  };

};

#endif
