// Generated by dia2code
#ifndef ENGINE__DIRECTIONCOMMAND__H
#define ENGINE__DIRECTIONCOMMAND__H


namespace state {
  class Character;
};
namespace engine {
  class Command;
}

#include "Command.h"
#include "state/Character.h"

namespace engine {

  /// class DirectionCommand - 
  class DirectionCommand : public engine::Command {
    // Associations
    // Attributes
  private:
    state::Character* character;
    int direction;
    // Operations
  public:
    DirectionCommand (state::Character* state, int direction);
    void execute ();
    // Setters and Getters
  };

};

#endif
