// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/State.h"
#include "Command.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  private:
    state::State* state;
    std::vector<Command*> commands;
    // Operations
  public:
    Engine ();
    void addCommand (Command* command);
    // Setters and Getters
  };

};

#endif
