// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <queue>
#include <stack>
#include <stdlib.h>

namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  public:
    bool reverse     = false;
  private:
    std::queue<Command*> commands;
    std::stack<Command*> rollback;
    // Operations
  public:
    void addCommand (Command* command);
    void runCommand ();
    void clearCommands ();
    std::size_t getSize ();
    // Setters and Getters
  };

};

#endif
