// Generated by dia2code
#ifndef ENGINE__FIGHTCOMMAND__H
#define ENGINE__FIGHTCOMMAND__H


namespace state {
  class Team;
  class State;
};
namespace engine {
  class Command;
}

#include "Command.h"
#include "state/Team.h"

namespace engine {

  /// class FightCommand - 
  class FightCommand : public engine::Command {
    // Associations
    // Attributes
  private:
    state::Team* att;
    state::Team* def;
    // Operations
  public:
    FightCommand (state::State* state, state::Team* att, state::Team* def);
    void execute ();
    // Setters and Getters
  };

};

#endif
