// Generated by dia2code
#ifndef ENGINE__MOVECOMMANDS__H
#define ENGINE__MOVECOMMANDS__H

#include "AStar.h"
#include <stdlib.h>
#include <vector>
#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Engine;
};
namespace state {
  class Character;
};
namespace engine {
  class MoveCommands;
  class Command;
}

#include "Command.h"

namespace engine {

  /// class MoveCommands - 
  class MoveCommands : public engine::Command {
    // Attributes
  private:
    int i;
    int j;
    AStar::Generator generator;
    std::size_t n;
    std::size_t m;
    // Operations
  public:
    MoveCommands (state::State* state, Engine* engine, state::Character* character, int i, int j, bool reverse = false);
    std::vector<int> getDiff ();
    std::vector<std::vector<int>> getPath ();
    void execute ();
    void const serialize (Json::Value& out);
    static MoveCommands* deserialize (const Json::Value& in, state::State* state, engine::Engine* engine = nullptr);
  private:
    void setGenerator ();
    // Setters and Getters
  };

};

#endif
