// Generated by dia2code
#ifndef ENGINE__MOVECOMMANDS__H
#define ENGINE__MOVECOMMANDS__H

#include <stdlib.h>
#include "AStar.h"
#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Engine;
};
namespace state {
  class Character;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class MoveCommands - 
  class MoveCommands : public engine::Command {
    // Attributes
  private:
    std::size_t i;
    std::size_t j;
    AStar::Generator generator;
    std::size_t n;
    std::size_t m;
    // Operations
  public:
    MoveCommands (state::State* state, Engine* engine, state::Character* character, std::size_t i, std::size_t j, bool reverse = false);
    std::vector<int> getDiff ();
    std::vector<std::vector<int>> getPath ();
    void execute ();
  private:
    void setGenerator ();
    // Setters and Getters
  };

};

#endif
