// Generated by dia2code
#ifndef ENGINE__MOVECOMMAND__H
#define ENGINE__MOVECOMMAND__H

#include <json/json.h>

namespace state {
  class State;
  class Character;
};
namespace engine {
  class MoveCommand;
  class Engine;
  class Command;
}

#include "Command.h"

namespace engine {

  /// class MoveCommand - 
  class MoveCommand : public engine::Command {
    // Attributes
  private:
    float i;
    float j;
    int pm;
    // Operations
  public:
    MoveCommand (state::State* state, state::Character* character, float i, float j, int pm = 0, bool reverse = false);
    void execute ();
    void const serialize (Json::Value& out);
    static MoveCommand* deserialize (const Json::Value& in, state::State* state, engine::Engine* engine = nullptr);
    // Setters and Getters
  };

};

#endif
