// Generated by dia2code
#ifndef ENGINE__MOVECOMMAND__H
#define ENGINE__MOVECOMMAND__H


namespace state {
  class State;
  class Character;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class MoveCommand - 
  class MoveCommand : public engine::Command {
    // Attributes
  private:
    float i;
    float j;
    // Operations
  public:
    MoveCommand (state::State* state, state::Character* character, float i, float j, bool reverse = false);
    void execute ();
    // Setters and Getters
  };

};

#endif
