// Generated by dia2code
#ifndef ENGINE__RESOURCECOMMAND__H
#define ENGINE__RESOURCECOMMAND__H

#include <vector>
#include <string>

namespace state {
  class Character;
  class State;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class ResourceCommand - 
  class ResourceCommand : public engine::Command {
    // Attributes
  private:
    std::vector<state::Character*> characters;
    std::vector<std::string> types;
    std::vector<int> values;
    // Operations
  public:
    ResourceCommand (state::State* state, std::vector<state::Character*> characters, std::vector<std::string> types, std::vector<int> values, bool reverse = false);
    void execute ();
    // Setters and Getters
  };

};

#endif
