// Generated by dia2code
#ifndef SERVER__GAME__H
#define SERVER__GAME__H


namespace state {
  class State;
};
namespace engine {
  class Engine;
};
namespace server {
  class PlayerDB;
  class Player;
}

#include "PlayerDB.h"
#include "Player.h"
#include "state/State.h"
#include "engine/Engine.h"
#include "GameStatus.h"

namespace server {

  /// class Game - 
  class Game {
    // Associations
    server::GameStatus status;
    // Attributes
  private:
    state::State* state;
    engine::Engine* engine;
  protected:
    PlayerDB playerDB;
    // Operations
  public:
    Game ();
    ~Game ();
    engine::Engine* getEngine ();
    void run ();
    // Setters and Getters
    GameStatus getStatus() const;
    void setStatus(GameStatus status);
    const PlayerDB& getPlayerDB() const;
    void setPlayerDB(const PlayerDB& playerDB);
  };

};

#endif
