// Generated by dia2code
#ifndef SERVER__PLAYER__H
#define SERVER__PLAYER__H

#include <string>

namespace server {

  /// class Player - 
  class Player {
    // Attributes
  public:
    std::string pseudo;
    bool isLogged;
    int teamId;
    // Operations
  public:
    Player (std::string pseudo = "", bool isLogged = true, int teamId = -1);
    // Setters and Getters
  };

};

#endif
