// Generated by dia2code
#ifndef SERVER__PLAYERDB__H
#define SERVER__PLAYERDB__H

#include <map>
#include <memory>

namespace server {
  class Player;
}

#include "Player.h"

namespace server {

  /// class PlayerDB - 
  class PlayerDB {
    // Associations
    // Attributes
  protected:
    int idseq;
    std::map<int,std::unique_ptr<Player>> players;
    // Operations
  public:
    PlayerDB ();
    const Player* getPlayer (int id) const;
    int addPlayer (std::unique_ptr<Player> players);
    void setPlayer (int id, std::unique_ptr<Player> players);
    void removePlayer (int id);
    // Setters and Getters
    int getIdseq() const;
    void setIdseq(int idseq);
    const std::map<int,std::unique_ptr<Player>>& getPlayers() const;
    void setPlayers(const std::map<int,std::unique_ptr<Player>>& players);
  };

};

#endif
