// Generated by dia2code
#ifndef SERVER__SERVICESMANAGER__H
#define SERVER__SERVICESMANAGER__H


namespace server {
  class AbstractService;
}

#include "AbstractService.h"
#include "HttpStatus.h"

namespace server {

  /// class ServicesManager - 
  class ServicesManager {
    // Associations
    // Attributes
  protected:
    vector<unique_ptr<AbstractService> > services;
    // Operations
  public:
    void registerService (unique_ptr<AbstractService> service);
    AbstractService* findService (const string& url) const;
    HttpStatus queryService (string& out, const string& in, const string& url, const string& method);
    // Setters and Getters
    const vector<unique_ptr<AbstractService> >& getServices() const;
    void setServices(const vector<unique_ptr<AbstractService> >& services);
  };

};

#endif
