// Generated by dia2code
#ifndef SERVER__SERVICESMANAGER__H
#define SERVER__SERVICESMANAGER__H

#include <vector>
#include <string>

namespace server {
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"

namespace server {

  /// class ServicesManager - 
  class ServicesManager {
    // Associations
    // Attributes
  protected:
    std::vector<AbstractService*> services;
    // Operations
  public:
    void registerService (AbstractService* service);
    AbstractService* findService (const std::string& url) const;
    HttpStatus queryService (std::string& out, const std::string& in, const std::string& url, const std::string& method);
    // Setters and Getters
    const std::vector<AbstractService*>& getServices() const;
    void setServices(const std::vector<AbstractService*>& services);
  };

};

#endif
