// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/Command.h"
#include "engine/Engine.h"
#include "engine/MoveCommand.h"
#include "engine/MoveCommands.h"
#include "engine/FightCommand.h"
#include "engine/AttackCommand.h"
#include "engine/AnimationCommand.h"
#include "engine/ClearCommand.h"
#endif
