// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/ComputeMethodType.h"
#include "render/Relatif.h"
#include "render/Relatif2.h"
#include "render/Element.h"
#include "render/Sprite.h"
#include "render/Rectangle.h"
#include "render/Text.h"
#include "render/Window.h"
#include "render/Inventory.h"
#include "render/WindowManager.h"
#include "render/View.h"
#include "render/Sprites.h"
#include "render/SpriteGeneratorById.h"
#include "render/Render.h"
#endif
