// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/ContentSprite.h"
#include "render/CharacterSprite.h"
#include "render/TileSprite.h"
#include "render/Render.h"
#endif
